tfa_sms.settings:
  type: config_object
  label: 'TFA SMS settings'
  mapping:
    sender:
      type: string
      label: 'Sender name'
    phone_prefix:
      type: string
      label: 'Phone number prefix'
    debug:
      type: boolean
      label: 'Enable debug logging' 